[package]
name = "stm4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
panic-probe = "1.0.0"
defmt = "1"
defmt-rtt = "1"
display-interface = "0.5.0"
ssd1306 = { version = "0.10.0", features = ["graphics"] }
u8g2-fonts = { version = "0.7.2", features = ["embedded_graphics_textstyle"] }
embedded-graphics = { version = "0.8.2", features = ["defmt"] }

[dependencies.stm32f4xx-hal]
version = "0.23.0"
features = ["stm32f411", "defmt"]

[profile.release]
debug = 2